#!/usr/bin/env python3
"""
Assemble stargazer-content.js from the readable sources in content/ and indigenous_star_knowledge.json.

  content/western.json   — one paragraph per constellation (IAU abbreviation -> text)
  content/origins.json   — where each constellation came from (era + a short history)
  content/showers.json   — annual meteor showers (IMO working list)
  content/events.json    — dated sky events (eclipses, oppositions, conjunctions, supermoons)
  content/figures.json   — how each Indigenous entry is drawn (label, constellations, figure type, bodies)
  indigenous_star_knowledge.json — the research file: entries with stories, sources, sensitivity, reviewer notes

Edit those files; never edit stargazer-content.js by hand. Usage: python3 tools/build_content.py
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')

def load(*p):
    return json.load(open(os.path.join(ROOT, *p), encoding='utf-8'))

def main():
    research = load('indigenous_star_knowledge.json')
    figures = load('content', 'figures.json')
    entries = []
    for e in research['entries'] + research.get('secondary_entries', []):
        f = figures.get(e['id'], {})
        if f.get('hold'):
            continue   # held back until reviewed by the tribal partner named in its notes
        fig = f.get('fig', 'cloud')
        entries.append({
            'id': e['id'], 'culture': e['culture'], 'name': e['name'],
            'label': f.get('label') or e['name'].split(' (')[0].split(';')[0].split(' /')[0].strip(),
            'translation': e.get('translation') or '', 'western': e['western'],
            'hip': [] if fig == 'none' else (e.get('hip') or []),
            'con': f.get('con', []), 'fig': fig, 'body': f.get('body', []),
            'story': e['story'], 'sensitivity': e['sensitivity'], 'confidence': e['confidence'],
            'sources': e['sources'], 'notes': e.get('notes', ''), 'sketch': f.get('sketch'), 'art': f.get('art')
        })
    out = {
        'framing': research['framing'],
        'indigenous': entries,
        'western': load('content', 'western.json'),
        'origins': load('content', 'origins.json'),
        'showers': load('content', 'showers.json'),
        'events': load('content', 'events.json'),
    }
    js = ('// StarGazer content bundle — generated by tools/build_content.py from content/*.json and indigenous_star_knowledge.json. '
          'Western constellation notes, Indigenous star knowledge (sources credited on each story), '
          'meteor showers (IMO 2026 calendar), and sky events 2026–2028 (NASA GSFC, EclipseWise, JPL).\n'
          'window.STARGAZER_CONTENT=') + json.dumps(out, separators=(',', ':'), ensure_ascii=False) + ';'
    open(os.path.join(ROOT, 'stargazer-content.js'), 'w', encoding='utf-8').write(js)
    print('wrote stargazer-content.js', round(len(js) / 1024), 'KB —', len(entries), 'Indigenous entries,', len(out['western']), 'constellations,', len(out['showers']), 'showers,', len(out['events']), 'events')

if __name__ == '__main__':
    main()
